[lock]
# Pantalla de bloqueo para el tema Minecraft
background       = "#F2F0E4"
background-alpha = 0.90
text             = "#221E18"
placeholder      = "#6B6250"
text-error       = "#B0433F"
border           = "#4E8A2A"
border-active    = "#2F6A14"
border-error     = "#B0433F"
border-alpha     = 1.0
selection        = "#4E8A2A"
selection-alpha  = 0.25
