[lock]
# Pantalla de bloqueo para el tema Lizarbe Minecraft
background       = "#EDE6CF"
background-alpha = 0.90
text             = "#2B2620"
placeholder      = "#8A7C66"
text-error       = "#B02E26"
border           = "#4E8B2F"
border-active    = "#2F6A14"
border-error     = "#B02E26"
border-alpha     = 1.0
selection        = "#4E8B2F"
selection-alpha  = 0.25
